name: Deploy to GoDaddy FTP

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: FTP Deploy to GoDaddy
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21  # change if you use SFTP
          local-dir: ./  # your project folder to upload, change if needed
          server-dir: /public_html  # GoDaddy hosting directory
